version: '3.7'

services:
  web:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=secret_chat

volumes:
  postgres_data: